# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e596860fca2ec1b59ea250ee16c0002c59c23803462229e43332edc68fd598d8d57b9fe0d9f812594561a9eeb2d5bf68862db148e4c3e217c8e485f55aebb813

test:
  secret_key_base: 6d79c84acf38ed89d81ccc621a569598f16b38bb21ca3e559c94fb55dcdcfe96f14c7e4574a6a9c3c98173ccc2e249ddf4d04012414f73bbf5363a60210c0216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
